### ISSUE TITLE
[Feature] Punishment for Loan

### ISSUE THREAD

**Issue by tn4799** [Courseplay/ChallengeMode_FS22#37]
Es wäre als Feature ganz cool, wenn es eine Regel geben würde, mit der man Minuspunkte für vorhandenen Kredit vergeben kann.
Z.B. Es gibt -1 Punkt für die Summe X an Kredit

_Originally posted by @BGDarktempler in https://github.com/Courseplay/ChallengeMode_FS22/issues/25#issuecomment-1415792023_

**Comment by Tensuko** [comment]
Kreditstraffe: aus/10k/50k/100k = je -1 Punkt.
