### ISSUE TITLE
[Feature] Punishment for spying on other farms

### ISSUE THREAD

**Issue by tn4799** [Courseplay/ChallengeMode_FS22#38]
Es wäre gut, wenn es eine Regel geben würde, mit der der Admin Einstellen kann, dass eine Farm einen Bestimmten Geldbetrag abgezogen bekommt, wenn ein Spieler dieser Farm sich die DetailPunkte einer Anderen Farm einsehen will. 
Beispielsweise dass jede Abfrage auf einer anderen Farm als die eigene einen Betrag von X vom Konto abzieht (Ins Minus gehen muss möglich sein - Alternativ wäre auch denkbar, dass die Punkte einer anderen Farm nur angezeigt werden können, wenn man über genügend Geld verfügt, um die Strafe zu zahlen)

_Originally posted by @BGDarktempler in https://github.com/Courseplay/ChallengeMode_FS22/issues/25#issuecomment-1415795446_

**Comment by Tensuko** [comment]
Statt Strafe, Rechte Detailliste ausblenden oder Zahlen mit X ersetzen.
Linke Seite die Farmen auch mit X anzeigen, möglichkeit durch Zahlen von Geld den Punktestand abfragen (beides als pop-up?)
